ENCODING

In [5]:
import pandas as pd

In [6]:
data=pd.DataFrame({"text":["people watch ineuron","ineuron watch ineuron","people write comment","ineuron write comment"],"output":[1,1,0,0]})

In [7]:
data.head()

text  output
0   people watch ineuron       1
1  ineuron watch ineuron       1
2   people write comment       0
3  ineuron write comment       0

In [ ]:
#Document Matrix(BOW)

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

In [9]:
# CountVectorizer library is used to convert a collection of text documents to a matrix of token counts
BOW=CountVectorizer()
document_matrix=BOW.fit_transform(data['text'])

In [10]:
document_matrix

<4x5 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [11]:
BOW.vocabulary_

{'people': 2, 'watch': 3, 'ineuron': 1, 'write': 4, 'comment': 0}

In [12]:
document_matrix[0].toarray() # 1st vector

array([[0, 1, 1, 1, 0]], dtype=int64)

In [13]:
document_matrix[1].toarray() # 2nd vector

array([[0, 2, 0, 1, 0]], dtype=int64)

In [14]:
document_matrix[2].toarray() # 3rd vector

array([[1, 0, 1, 0, 1]], dtype=int64)

In [16]:
document_matrix[3].toarray() # 4th vector

array([[1, 1, 0, 0, 1]], dtype=int64)

In [19]:
# parameter N-GRAM RANGE in CountVectorizer , it is used to specify the range of n-grams to be extracted

# 1st will try Bi-GRAM = it will consider 2 words at a time

bigram=CountVectorizer(ngram_range=(2,2))
bigramvocab=bigram.fit_transform(data['text'])

In [20]:
bigram.vocabulary_

{'people watch': 2,
 'watch ineuron': 4,
 'ineuron watch': 0,
 'people write': 3,
 'write comment': 5,
 'ineuron write': 1}

In [21]:
# 2nd will try Tri-GRAM = it will consider 3 words at a time

trigram=CountVectorizer(ngram_range=(3,3))
trigramvocab=trigram.fit_transform(data['text'])

In [22]:
trigram.vocabulary_

{'people watch ineuron': 2,
 'ineuron watch ineuron': 0,
 'people write comment': 3,
 'ineuron write comment': 1}

In [23]:
# to include both 1 and 1 gram (mix of both)

mix=CountVectorizer(ngram_range=(1,2))
mixvocab=mix.fit_transform(data['text'])

In [24]:
mix.vocabulary_

{'people': 4,
 'watch': 7,
 'ineuron': 1,
 'people watch': 5,
 'watch ineuron': 8,
 'ineuron watch': 2,
 'write': 9,
 'comment': 0,
 'people write': 6,
 'write comment': 10,
 'ineuron write': 3}

In [ ]:
# TF-IDF (Term Frequency-Inverse Document Frequency)
# it is used to convert the document matrix into a normalized form

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()

In [30]:
tfidf.fit_transform(data['text']).toarray()

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [32]:
tfidf.get_feature_names_out()

array(['comment', 'ineuron', 'people', 'watch', 'write'], dtype=object)

In [33]:
tfidf.vocabulary_

{'people': 2, 'watch': 3, 'ineuron': 1, 'write': 4, 'comment': 0}

In [35]:
tfidf.idf_

array([1.51082562, 1.22314355, 1.51082562, 1.51082562, 1.51082562])